from flask import Flask
from model import *
import uuid
import datetime

app = Flask(__name__)


@app.route('/js/crowd-captcha.js', methods=["POST"])
def js():
    # Takes:
    #   - an application uuid.

    # Does:
    #     Process the application uuid and generates a valid js file.
    #     That file contains the questions (fetched from the Text
    #     entity) and displays a dialog from the user side.

    # Returns:
    #   - a valid JS with questions.
    pass


@app.route('/api/v1/tag', methods=["POST"])
def tag():
    # Takes
    #   - an application uuid.
    #   - a user uuid.
    #   - a list of responses (text_uuid and a tag)

    # Does:
    #     This function is called from the JS generated by the js()
    #     endpoint. It creates Tag entities (the answers) and also
    #     creates a Secret.

    # Returns:
    #   - a secret uuid to be validated later.

    pass


@app.route('/api/v1/validate', methods=["POST"])
def validate():
    # Takes
    #   - an application uuid
    #   - a user id
    #   - a secret

    # Does:
    #     Returns "ok" if the secret hasn't expired and is valid for the
    #     application and the user. Otherwise it returns "error" (400).
    #     Marks all the relevant tags as "validated".

    # Returns:
    #   - whether the secret was valid or not.
    pass


if __name__ == "__main__":
    app.run(host='0.0.0.0', port=8181, debug=True)
